# Generated by Django 3.1.5 on 2021-02-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210212_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default-profile-picture.png', upload_to='profile_pictures'),
        ),
    ]
