# Generated by Django 3.1.6 on 2021-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210212_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='small_biography',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
