# Generated by Django 3.1.5 on 2021-02-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default-service.jpg', upload_to='advertisements'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default-service.jpg', upload_to='services'),
        ),
    ]
